export const countryFlags: Record<string, string> = {
    Albania: '🇦🇱',
    Armenia: '🇦🇲',
    Australia: '🇦🇺',
    Austria: '🇦🇹',
    Azerbaijan: '🇦🇿',
    Belgium: '🇧🇪',
    Bulgaria: '🇧🇬',
    Croatia: '🇭🇷',
    Cyprus: '🇨🇾',
    Czechia: '🇨🇿',
    Denmark: '🇩🇰',
    Estonia: '🇪🇪',
    Finland: '🇫🇮',
    France: '🇫🇷',
    Georgia: '🇬🇪',
    Germany: '🇩🇪',
    Greece: '🇬🇷',
    Israel: '🇮🇱',
    Italy: '🇮🇹',
    Latvia: '🇱🇻',
    Lithuania: '🇱🇹',
    Luxembourg: '🇱🇺',
    Malta: '🇲🇹',
    Moldova: '🇲🇩',
    Montenegro: '🇲🇪',
    Norway: '🇳🇴',
    Poland: '🇵🇱',
    Portugal: '🇵🇹',
    Romania: '🇷🇴',
    'San Marino': '🇸🇲',
    Serbia: '🇷🇸',
    Sweden: '🇸🇪',
    Switzerland: '🇨🇭',
    Ukraine: '🇺🇦',
    'United Kingdom': '🇬🇧',
};
